export enum GOV_SYNC_JOB_STATUS {
  QUEUED = 'QUEUED',
  RUNNING = 'RUNNING',
  WAITING_EXTERNAL = 'WAITING_EXTERNAL',
  PARTIALLY_COMPLETED = 'PARTIALLY_COMPLETED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

